-- ══════════════════════════════════════════════════════════════
-- Mealcule — Ingredient Data Migration
-- Generated: 2026-03-29T15:42:29.254Z
-- Total ingredients: 136
-- ══════════════════════════════════════════════════════════════

-- First ensure categories exist with local mapping
INSERT INTO public.categories (id, label, label_en, emoji, sort_order) VALUES
  ('veg', '채소', 'Vegetables', '🥬', 3)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.categories (id, label, label_en, emoji, sort_order) VALUES
  ('sauce', '소스/양념', 'Sauces', '🧂', 9)
ON CONFLICT (id) DO NOTHING;

-- Ingredient data
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('소고기', 'meat', '🥩', 200, 26, 15, 0, 59, 0, '["글루탐산","리신","류신"]', 0, 0, 0, 0, 0, 0, 0, 0.4, 2.6, 0, 5.1, 0, 0, 0, 2.6, 4.8, '["미오글로빈","콜라겐","크레아틴","카르노신"]', 80, 10, 5, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('돼지고기', 'meat', '🥓', 200, 27, 14, 0, 58, 0, '["글루탐산","리신","류신"]', 0, 0, 0, 0, 0, 0.73, 0, 0.5, 0, 0, 8.9, 0, 0, 0, 2.2, 2.8, '["미오글로빈","카르니틴","크레아틴"]', 75, 8, 5, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('닭가슴살', 'meat', '🍗', 200, 31, 3.6, 0, 65, 0, '["류신","리신","메티오닌"]', 0, 0, 0, 0, 0, 0, 0, 0.88, 0, 0, 9.9, 0, 0, 0, 0, 0, '["미오글로빈","카르노신","안세린"]', 60, 5, 5, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('닭다리', 'meat', '🍗', 200, 26, 8, 0, 65, 0, '["류신","리신"]', 0, 0, 0, 0, 0, 0, 0, 0.4, 0, 0, 6.2, 0, 0, 0, 1.4, 2.8, '["미오글로빈","콜라겐"]', 65, 6, 5, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('양고기', 'meat', '🐑', 200, 25, 16, 0, 58, 0, '["글루탐산","류신","리신"]', 0, 0, 0, 0, 0, 0, 0, 0.3, 2.4, 0, 0, 0, 0, 0, 2.3, 0, '["미오글로빈","카르노신","카르니틴"]', 78, 10, 6, 0, 6, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('오리고기', 'meat', '🦆', 200, 19, 28, 0, 52, 0, '["글루탐산","류신"]', 0, 0, 0, 0, 0, 0, 0, 0, 2.8, 0, 0, 0, 0, 0, 3.8, 3.2, '["미오글로빈","철분"]', 70, 8, 5, 0, 8, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('베이컨', 'meat', '🥓', 30, 37, 61, 0, 1, 0, '["류신","리신"]', 0, 0, 0, 0, 0, 0.62, 0, 0.5, 0, 0, 6.8, 0, 0, 0, 0, 0, '["니트로사민","스모키 향료"]', 85, 5, 85, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('소시지', 'meat', '🌭', 50, 12, 28, 4, 55, 0, '["류신","리신"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1100, 0, 0, 0.9, 0, '["니트라이트","타우린"]', 75, 10, 75, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('햄', 'meat', '🍖', 50, 13, 6.5, 1.5, 79, 0, '["류신","리신"]', 0, 0, 0, 0, 0, 0.53, 0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0, '["니트라이트","글루탐산"]', 70, 8, 70, 3, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('연어', 'seafood', '🐟', 150, 25, 11, 0, 63, 0, '["류신","리신","메티오닌"]', 0, 0, 12.5, 0, 0, 0, 0, 0, 3.2, 0, 0, 0, 0, 0, 0, 0, '["아스타잔틴","오메가-3","카르노신"]', 70, 8, 5, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('참치', 'seafood', '🐟', 150, 29, 1.3, 0, 69, 0, '["류신","리신"]', 0, 0, 0, 0, 0, 0, 0, 0, 9.3, 0, 7.2, 0, 0, 0, 0, 0, '["미오글로빈","아스타잔틴","타우린"]', 80, 10, 5, 5, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('새우', 'seafood', '🦐', 100, 24, 0.3, 0, 75, 0, '["류신","리신","메티오닌"]', 0, 0, 0, 0, 0, 0, 0, 0, 1.68, 0, 0, 0, 0, 52, 0, 0, '["아스타잔틴","타우린","퀵토산"]', 75, 8, 5, 5, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('고등어', 'seafood', '🐟', 150, 20, 13, 0, 66, 0, '["류신","리신"]', 0, 0, 17.6, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, '["아스타잔틴","오메가-3"]', 75, 8, 5, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('오징어', 'seafood', '🦑', 100, 15, 0.4, 3, 81, 0, '["류신","리신"]', 0, 0, 0, 0, 0, 0, 0, 0, 0.48, 0, 0, 0, 0, 0, 0, 0, '["타우린","키토산","글루탐산"]', 75, 5, 5, 5, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('조개', 'seafood', '🦪', 100, 12, 0.5, 4.5, 82, 0, '["류신","리신"]', 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 28, 9.2, '["타우린","글리신"]', 80, 15, 5, 10, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('게', 'seafood', '🦀', 100, 19, 1, 0, 79, 0, '["류신","리신","메티오닌"]', 0, 0, 0, 0, 0, 0, 0, 0, 9.8, 0, 0, 0, 0, 278, 0, 4.1, '["키토산","타우린"]', 80, 10, 8, 5, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('문어', 'seafood', '🐙', 100, 18, 0.8, 0, 80, 0, '["류신","리신"]', 0, 0, 0, 0, 0, 0, 0, 0, 17.66, 0, 0, 0, 0, 0, 0, 0, '["타우린","폴리아민"]', 78, 5, 5, 5, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('꽁치', 'seafood', '🐟', 150, 19, 13, 0, 67, 0, '["류신","리신"]', 0, 0, 13, 0, 0, 0, 0, 0, 9.9, 0, 0, 0, 0, 0, 0, 0, '["오메가-3","아스타잔틴"]', 72, 8, 5, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('대구', 'seafood', '🐟', 150, 17, 0.7, 0, 82, 0, '["류신","리신"]', 0, 0, 0, 0, 0, 0, 0, 0, 1.6, 0, 0, 0, 0, 0, 0, 0, '["타우린","글리신"]', 70, 5, 5, 5, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('광어', 'seafood', '🐟', 150, 20, 1.5, 0, 78, 0, '["류신","리신"]', 0, 0, 5.1, 0, 0, 0, 0, 0, 1.8, 0, 0, 0, 0, 0, 0, 0, '["타우린","글리신"]', 75, 5, 5, 5, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('멸치', 'seafood', '🐟', 30, 66, 3, 0, 17, 0, '["류신","리신"]', 0, 0, 0, 0, 0, 0, 0, 0, 51, 0, 0, 0, 0, 520, 18, 0, '["타우린","칼슘"]', 90, 5, 60, 5, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('전복', 'seafood', '🐚', 100, 19, 1, 2, 77, 0, '["글리신","류신"]', 0, 0, 0, 0, 0, 0, 0, 0, 5.7, 0, 0, 0, 0, 166, 4, 0, '["타우린","키토산"]', 80, 15, 5, 8, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('양파', 'veg', '🧅', 150, 1.1, 0.1, 9.3, 89, 1.7, '["시스테인"]', 0, 7.4, 0, 0, 0, 0, 0, 0.12, 0, 19, 0, 0, 146, 0, 0, 0, '["알리신","퀘르세틴","프로필 설파이드","프럭토올리고당"]', 20, 40, 0, 5, 15, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('마늘', 'veg', '🧄', 10, 6.4, 0.5, 33, 59, 2.1, '["시스테인","메티오닌"]', 0, 31, 0, 0, 0, 0, 0, 1.24, 0, 0, 0, 0, 0, 0, 0, 0, '["알리신","알리인","디알릴 설파이드","아조엔"]', 30, 10, 0, 5, 20, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('감자', 'veg', '🥔', 200, 2, 0.1, 17, 79, 2.2, '["아스파르트산","글루탐산"]', 0, 19.7, 0, 0, 0, 0, 0, 0.3, 0, 0, 0, 0, 425, 0, 0, 0, '["전분(아밀로스)","솔라닌","클로로겐산","아스파라긴"]', 10, 15, 0, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('토마토', 'veg', '🍅', 150, 0.9, 0.2, 3.9, 94, 1.2, '["글루탐산"]', 42, 14, 0, 0, 7.9, 0, 0, 0, 0, 0, 0, 0, 237, 0, 0, 0, '["리코펜","글루탐산","시트르산","나린게닌"]', 60, 25, 0, 40, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('고추', 'veg', '🌶️', 15, 1.9, 0.4, 8.8, 88, 1.5, '[]', 48, 144, 0, 0, 0, 0, 0, 0.51, 0, 0, 0, 0, 322, 0, 0, 0, '["캡사이신","디하이드로캡사이신","카로티노이드"]', 5, 15, 0, 5, 10, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('브로콜리', 'veg', '🥦', 100, 2.8, 0.4, 7, 89, 2.4, '["글루탐산","아스파르트산"]', 0, 89, 0, 0, 102, 0, 0, 0, 0, 63, 0, 0, 0, 47, 0, 0, '["설포라판","인돌","캐롤","클로로필"]', 25, 10, 0, 5, 25, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('당근', 'veg', '🥕', 100, 0.9, 0.2, 10, 88, 2.8, '[]', 835, 0, 0, 0, 13.2, 0, 0, 0, 0, 0, 0, 0, 320, 0, 0, 0, '["베타카로틴","리코펜","루테올린"]', 10, 35, 0, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('시금치', 'veg', '🥬', 100, 2.7, 0.4, 3.6, 91, 2.2, '["글루탐산"]', 469, 28, 0, 0, 483, 0, 0, 0, 0, 194, 0, 0, 0, 0, 2.7, 0, '["루테인","비올란틴","클로로필"]', 30, 5, 0, 5, 20, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('배추', 'veg', '🥬', 100, 1.2, 0.2, 3.2, 95, 1, '[]', 0, 21, 0, 0, 63, 0, 0, 0, 0, 0, 0, 0, 0, 77, 0, 0, '["카로틴","클로로필","설포라판"]', 15, 10, 0, 5, 10, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('파프리카', 'veg', '🫑', 100, 0.9, 0.3, 6, 92, 2, '[]', 314, 80, 0, 0, 0, 0, 0, 0.3, 0, 0, 0, 0, 211, 0, 0, 0, '["캡산토인","카로티노이드"]', 15, 45, 0, 10, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('양배추', 'veg', '🥬', 100, 1.3, 0.1, 5.2, 92, 2.4, '["글루탐산"]', 0, 36.6, 0, 0, 101, 0, 0, 0, 0, 43, 0, 0, 0, 0, 0, 0, '["설포라판","인돌","카로티노이드"]', 15, 15, 0, 5, 15, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('오이', 'veg', '🥒', 150, 0.7, 0.2, 3.6, 95, 0.5, '[]', 0, 2.8, 0, 0, 16.4, 0, 0, 0, 0, 0, 0, 0, 147, 0, 0, 0, '["큐커비타신","클로로필"]', 5, 5, 0, 10, 10, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('호박', 'veg', '🎃', 100, 1, 0.1, 5, 94, 0.5, '[]', 426, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 340, 0, 0, 0, '["베타카로틴","루테인"]', 10, 20, 0, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('가지', 'veg', '🍆', 100, 1.1, 0.2, 5.2, 92, 3, '[]', 0, 3.5, 0, 0, 29, 0, 0, 0, 0, 0, 0, 0, 229, 0, 0, 0, '["알카로이드","안토시아닌"]', 15, 5, 0, 5, 15, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('셀러리', 'veg', '🌿', 100, 0.7, 0.1, 3.7, 95, 1.6, '[]', 0, 3.1, 0, 0, 29.3, 0, 0, 0, 0, 0, 0, 0, 260, 0, 0, 0, '["3-n-부틸프탈라이드","루테올린"]', 10, 5, 0, 10, 15, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('아스파라거스', 'veg', '🥒', 100, 2.2, 0.1, 3.7, 93, 2.1, '["글루탐산"]', 38, 5.6, 0, 0, 91.5, 0, 0, 0, 0, 52, 0, 0, 0, 0, 0, 0, '["루틴","글루타치온"]', 25, 5, 0, 5, 10, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('무', 'veg', '🌰', 100, 0.7, 0.1, 3.4, 95, 1.6, '[]', 0, 25, 0, 0, 1.3, 0, 0, 0, 0, 0, 0, 0, 233, 0, 0, 0, '["미로시나아제","글루코시놀레이트"]', 5, 5, 0, 20, 10, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('콩나물', 'veg', '🌱', 100, 3.1, 0.2, 6, 90, 1, '["류신","리신"]', 0, 20, 0, 0, 34, 0, 0, 0, 0, 95, 0, 0, 0, 0, 0, 0, '["사포닌","이소플라본"]', 10, 10, 0, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('부추', 'veg', '🌿', 100, 2.4, 0.4, 6.2, 90, 1.3, '[]', 77, 23, 0, 0, 213, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["알리신","퀘르세틴"]', 20, 10, 0, 5, 15, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('파', 'veg', '🌿', 100, 1.9, 0.3, 7.3, 89, 1.4, '[]', 110, 18, 0, 0, 103, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["알리신","퀘르세틴"]', 15, 15, 0, 5, 15, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('미나리', 'veg', '🌿', 100, 2.1, 0.1, 4.1, 93, 1, '[]', 337, 41, 0, 0, 145, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["데카날데하이드","데카놀"]', 10, 5, 0, 5, 15, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('피망', 'veg', '🫑', 100, 0.9, 0.3, 6, 92, 2, '[]', 314, 80, 0, 0, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["캡산토인","카로티노이드"]', 15, 40, 0, 10, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('비트', 'veg', '🥗', 100, 1.6, 0.2, 9.6, 88, 2.8, '["베타인"]', 0, 4.9, 0, 0, 0.5, 0, 0, 0, 0, 109, 0, 0, 325, 0, 0, 0, '["베타인","베타라닌","안토시아닌"]', 15, 30, 0, 10, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('케일', 'veg', '🥬', 100, 3.3, 0.7, 6.6, 84, 1.3, '["글루탐산","알라닌"]', 478, 120, 0, 0, 704, 0, 0, 0, 0, 0, 0, 0, 0, 254, 0, 0, '["설포라판","루테인","루틴"]', 25, 5, 0, 5, 30, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('고구마', 'veg', '🍠', 100, 1.6, 0.1, 20, 77, 3, '[]', 961, 8.8, 0, 0, 0, 0, 0, 0.28, 0, 0, 0, 0, 337, 0, 0, 0, '["베타카로틴","안토시아닌"]', 5, 40, 0, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('옥수수', 'veg', '🌽', 100, 3.2, 1.2, 19, 76, 2.7, '["루신"]', 0, 6.8, 0, 0, 0, 0.39, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["루테인","지아잔틴"]', 10, 25, 0, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('사과', 'fruit', '🍎', 150, 0.3, 0.2, 14, 85, 2.4, '[]', 0, 5.7, 0, 0, 3.7, 0, 0, 0, 0, 0, 0, 0, 195, 0, 0, 0, '["퀘르세틴","클로로겐산","프로시아니딘"]', 5, 45, 0, 15, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('바나나', 'fruit', '🍌', 100, 1.1, 0.3, 23, 75, 2.6, '["트립토판","세로토닌"]', 0, 8.7, 0, 0, 0, 0, 0, 0.4, 0, 0, 0, 0, 358, 0, 0, 0, '["푼오이신","세로토닌"]', 5, 50, 0, 5, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('딸기', 'fruit', '🍓', 100, 0.7, 0.3, 8, 91, 2, '[]', 0, 58.8, 0, 0, 2.2, 0, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, '["엘라그산","안토시아닌","카테킨"]', 5, 40, 0, 20, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('블루베리', 'fruit', '🫐', 100, 0.7, 0.3, 14, 84, 2.4, '[]', 0, 9.7, 0, 0, 19.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["안토시아닌","카테킨","리사린"]', 5, 35, 0, 15, 10, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('아보카도', 'fruit', '🥑', 100, 2, 15, 9, 73, 7, '["글루탐산"]', 0, 10, 0, 0, 21, 0, 0, 0, 0, 0, 0, 0, 485, 0, 0, 0, '["글루타치온","카로티노이드"]', 15, 5, 0, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('포도', 'fruit', '🍇', 100, 0.7, 0.4, 17, 81, 0.9, '[]', 0, 3.2, 0, 0, 191, 0, 0, 0, 0, 0, 0, 0, 191, 0, 0, 0, '["레스베라트롤","탄닌","안토시아닌"]', 5, 50, 0, 10, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('수박', 'fruit', '🍉', 150, 0.6, 0.2, 12, 87, 0.4, '[]', 28, 8.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["시트룰린","리코펜"]', 5, 40, 0, 10, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('키위', 'fruit', '🥝', 100, 1.1, 0.5, 15, 83, 3, '["글루탐산"]', 0, 92.7, 0, 0, 312, 0, 0, 0, 0, 0, 0, 0, 312, 0, 0, 0, '["악티니딘","플라보노이드"]', 5, 40, 0, 25, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('레몬', 'fruit', '🍋', 30, 1.1, 0.3, 9.3, 89, 2.8, '[]', 0, 53, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 138, 0, 0, 0, '["시트르산","리모넨","아스코르브산","헤스페리딘"]', 0, 10, 0, 90, 15, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('오렌지', 'fruit', '🍊', 100, 0.7, 0.2, 12, 87, 2.4, '[]', 0, 53.2, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 181, 0, 0, 0, '["플라보노이드","나린게닌","헤스페리딘"]', 5, 45, 0, 15, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('자몽', 'fruit', '🍊', 100, 0.8, 0.1, 13, 86, 1.6, '[]', 0, 33.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0, 0, '["나린진","푸라노쿠마린","리모노이드"]', 5, 35, 0, 35, 20, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('망고', 'fruit', '🥭', 100, 0.7, 0.3, 15, 84, 1.6, '[]', 765, 36.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 168, 0, 0, 0, '["망기페린","안토시아닌"]', 5, 55, 0, 10, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('파인애플', 'fruit', '🍍', 100, 0.5, 0.1, 13, 86, 1.4, '[]', 0, 47.8, 0, 0, 0, 0, 0, 0.11, 0, 0, 0, 0, 109, 0, 0, 0, '["브로멜라인","프로산토시아니딘"]', 5, 45, 0, 30, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('복숭아', 'fruit', '🍑', 100, 0.9, 0.3, 10, 89, 1.5, '[]', 16, 6.6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 190, 0, 0, 0, '["엘라그산","클로로겐산"]', 5, 45, 0, 10, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('배', 'fruit', '🍐', 100, 0.4, 0.1, 15, 84, 3.1, '[]', 0, 4.6, 0, 0, 1.6, 0, 0, 0, 0, 0, 0, 0, 116, 0, 0, 0, '["아라분","클로로겐산"]', 5, 40, 0, 10, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('감', 'fruit', '🍂', 100, 0.8, 0.3, 19, 80, 1.6, '[]', 81, 7.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 161, 0, 0, 0, '["탄닌","카로티노이드"]', 5, 55, 0, 5, 10, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('밀가루', 'grain', '🌾', 30, 10, 1, 76, 11, 2.7, '["글루텐","글리아딘"]', 0, 0, 0, 0, 0, 0.12, 0.07, 0, 0, 0, 0.6, 0, 0, 0, 4.6, 0, '["글루텐","카로티노이드"]', 10, 15, 0, 0, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('파스타', 'grain', '🍝', 100, 13, 1.1, 75, 10, 1.8, '["글루탐산"]', 0, 0, 0, 0, 0, 0.28, 0.1, 0, 0, 0, 2, 0, 0, 0, 1.3, 0, '["글루텐","전분"]', 15, 10, 0, 0, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('귀리', 'grain', '🌾', 50, 17, 7, 66, 8, 10.6, '["글루탐산"]', 0, 0, 0, 0, 0, 0.76, 0, 0, 0, 0, 0, 0, 0, 0, 4.7, 0, '["베타글루칸","아베나안토사이드"]', 15, 15, 0, 0, 10, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('메밀', 'grain', '🌾', 30, 13, 3, 71, 12, 10, '["글루탐산"]', 0, 0, 0, 0, 0, 0.1, 0.44, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["루틴","플라보노이드"]', 10, 10, 0, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('현미', 'grain', '🍚', 150, 3, 1, 28, 68, 0.8, '["글루탐산"]', 0, 0, 0, 0, 0, 0.12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["감마오리자놀","토코트리에놀"]', 10, 20, 0, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('쌀', 'grain', '🍚', 150, 2.7, 0.3, 28, 69, 0.4, '["글루탐산"]', 0, 0, 0, 0, 0, 0.02, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0, '["아밀로스","아밀로펙틴","감마오리자놀"]', 10, 20, 0, 0, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('식빵', 'grain', '🍞', 30, 8, 2, 49, 38, 2.4, '["글루텐"]', 0, 0, 0, 0, 0, 0.12, 0.07, 0, 0, 32, 0, 0, 0, 0, 0, 0, '["글루텐","몰드","효모"]', 15, 15, 10, 5, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('우동면', 'grain', '🍜', 100, 9, 0.3, 62, 28, 1.8, '["글루탐산"]', 0, 0, 0, 0, 0, 0.14, 0.08, 0, 0, 0, 1.2, 0, 0, 0, 0, 0, '["글루텐","전분"]', 20, 10, 15, 0, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('라면(건면)', 'grain', '🍜', 100, 8, 3, 65, 13, 2, '["글루탐산"]', 0, 0, 0, 0, 0, 0.12, 0.07, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["글루텐","전분"]', 25, 10, 50, 5, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('우유', 'dairy', '🥛', 200, 3.2, 3.6, 4.8, 87, 0, '["류신","리신","메티오닌"]', 28, 0, 0.06, 0, 0, 0, 0, 0, 0.4, 0, 0, 0, 0, 113, 0, 0, '["카제인","유청","락토스"]', 20, 20, 10, 5, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('치즈', 'dairy', '🧀', 30, 25, 33, 1, 37, 0, '["류신","리신"]', 721, 0, 0, 0, 0, 0, 0, 0, 1.3, 0, 0, 0, 0, 721, 0, 0, '["카제인","지방","락토스"]', 65, 5, 50, 10, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('크림', 'dairy', '🍶', 30, 2.3, 34, 3, 61, 0, '["류신"]', 1000, 0, 0.3, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0, '["지방","카제인"]', 10, 15, 10, 5, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('요거트', 'dairy', '🥛', 150, 3.5, 0.4, 4, 88, 0, '["류신","리신"]', 0, 0, 0, 0, 0, 0, 0, 0, 0.3, 0, 0, 0, 0, 121, 0, 0, '["프로바이오틱스","락토스"]', 15, 15, 5, 30, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('생크림', 'dairy', '🍶', 30, 2, 35, 2.8, 60, 0, '[]', 1200, 0, 0.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["지방","카제인"]', 5, 15, 10, 5, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('모짜렐라', 'dairy', '🧀', 30, 28, 17, 3.1, 51, 0, '["류신","리신"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 505, 0, 0, '["카제인"]', 45, 5, 40, 10, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('파르메산', 'dairy', '🧀', 10, 38, 29, 4, 27, 0, '["글루탐산"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1109, 0, 0, '["글루탐산나트륨","카제인"]', 80, 0, 60, 10, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('계란', 'egg', '🥚', 60, 13, 11, 1.1, 75, 0, '["류신","리신","메티오닌","트립토판"]', 160, 0, 2, 0, 0, 0, 0, 0, 0.89, 0, 0, 0, 0, 0, 0, 0, '["오보알부민","오보뮤코이드","레시틴","루테인"]', 30, 5, 5, 0, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('메추리알', 'egg', '🥚', 10, 13, 11, 0.4, 74, 0, '["류신","리신"]', 0, 0, 0, 0, 0, 0, 0, 0, 0.64, 0, 0, 0, 0, 0, 0, 0, '["오보알부민"]', 25, 5, 5, 0, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('오리알', 'egg', '🥚', 70, 13, 14, 0.9, 72, 0, '["류신","리신"]', 0, 0, 0, 0, 0, 0, 0, 0, 0.92, 0, 0, 0, 0, 0, 0, 0, '["오보알부민"]', 30, 5, 5, 0, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('아몬드', 'nut', '🥜', 30, 21, 50, 22, 4, 12.5, '["글루탐산"]', 0, 0, 0, 25.6, 0, 0, 1.14, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["플라보노이드","폴리페놀"]', 25, 10, 0, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('호두', 'nut', '🥜', 30, 9, 65, 14, 4, 6.7, '["글루탐산"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["폴리페놀","탄닌"]', 20, 5, 0, 0, 10, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('땅콩', 'nut', '🥜', 30, 26, 49, 20, 3, 6, '["글루탐산","아르기닌"]', 0, 0, 0, 8.3, 0, 0.64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["리놀레산","폴리페놀"]', 25, 15, 0, 0, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('캐슈넛', 'nut', '🥜', 30, 18, 49, 30, 2, 3.3, '["글루탐산"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["탄닌","플라보노이드"]', 20, 20, 0, 0, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('잣', 'nut', '🥜', 30, 14, 68, 13, 2, 3.7, '["글루탐산"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["폴리페놀"]', 25, 15, 0, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('참깨', 'nut', '🥜', 15, 18, 52, 23, 5, 11.8, '["메티오닌"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 975, 0, 0, '["리그난","세사몰"]', 20, 10, 0, 0, 10, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('들깨', 'nut', '🥜', 15, 19, 45, 26, 4, 27.3, '["글루탐산"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["리그난"]', 25, 10, 0, 0, 15, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('해바라기씨', 'nut', '🥜', 30, 20, 51, 20, 4, 8.6, '["글루탐산"]', 0, 0, 0, 41.1, 0, 1.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["리놀레산"]', 20, 10, 0, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('표고버섯', 'mushroom', '🍄', 100, 2.2, 0.3, 7.3, 89, 1, '["글루탐산"]', 0, 0, 0.81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["에르고티오네인","렌티난"]', 45, 5, 0, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('양송이', 'mushroom', '🍄', 100, 3.3, 0.3, 3.3, 92, 1, '["글루탐산"]', 0, 0, 0, 0, 0, 0, 0.4, 0, 0, 0, 3.6, 0, 0, 0, 0, 0, '["에르고티오네인"]', 35, 5, 0, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('팽이버섯', 'mushroom', '🍄', 100, 2.7, 0.3, 6.9, 89, 2, '["글루탐산"]', 0, 0, 0, 0, 0, 0.04, 0.22, 0, 0, 0, 3.9, 0, 0, 0, 0, 0, '["렌티난","베타글루칸"]', 35, 5, 0, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('새송이', 'mushroom', '🍄', 100, 3.4, 0.5, 5.7, 90, 1, '["글루탐산"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4.7, 0, 0, 0, 0, 0, '["렌티난"]', 40, 5, 0, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('목이버섯', 'mushroom', '🍄', 100, 8.8, 0.2, 65, 12, 6.6, '["글루탐산"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 185, 0, '["다당류"]', 30, 5, 0, 5, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('느타리', 'mushroom', '🍄', 100, 3.3, 0.2, 7, 88, 1.1, '["글루탐산"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3.5, 0, 0, 0, 0, 0, '["렌티난"]', 40, 5, 0, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('검은콩', 'legume', '🫘', 100, 9, 1, 17, 71, 6, '["글루탐산","리신","류신"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 44, 0, 0, 0, 0, 0, 0, '["안토시아닌","이소플라본"]', 25, 5, 0, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('렌틸콩', 'legume', '🫘', 100, 25, 0.4, 20, 11, 8, '["리신","류신","글루탐산"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 181, 0, 0, 0, 0, 6.5, 0, '["폴리페놀","사포닌"]', 30, 5, 0, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('병아리콩', 'legume', '🫘', 100, 19, 6, 27, 11, 6, '["글루탐산","리신"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 172, 0, 0, 0, 0, 4.3, 0, '["이소플라본","사포닌"]', 25, 10, 0, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('팥', 'legume', '🫘', 100, 9, 0.3, 20, 71, 5, '["글루탐산","리신"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 159, 0, 0, 0, 0, 5.5, 0, '["안토시아닌","폴리페놀"]', 20, 10, 0, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('완두콩', 'legume', '🫘', 100, 5, 0.4, 7, 88, 2.4, '["글루탐산","리신"]', 0, 40, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["이소플라본"]', 15, 15, 0, 0, 3, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('된장(식재료)', 'legume', '🫘', 15, 12, 5, 10, 67, 2, '["글루탐산"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4030, 0, 0, 1.8, 0, '["멜라노이딘","글루탐산나트륨"]', 85, 10, 80, 10, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('두부', 'legume', '🧊', 150, 8, 4.8, 1.9, 85, 0.3, '["류신","리신"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 350, 5.4, 0, '["이소플라본","제니스테인","다이드제인","사포닌"]', 25, 5, 0, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('바질', 'herb', '🌿', 3, 3.2, 0.6, 2.7, 92, 1.6, '[]', 264, 18, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["에센셜오일","리나롤","유게놀"]', 15, 10, 0, 5, 10, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('로즈마리', 'herb', '🌿', 3, 3.3, 5.3, 21, 69, 14.1, '[]', 20, 21.8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["카르노솔","올레산"]', 10, 5, 0, 5, 20, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('타임', 'herb', '🌿', 3, 5.6, 1.7, 24, 65, 18.5, '[]', 27, 50, 0, 0, 401, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["티몰","카르바크롤"]', 15, 5, 0, 5, 20, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('민트', 'herb', '🌿', 3, 3.8, 0.9, 6.4, 85, 2.8, '[]', 212, 31.8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["멘톨","멘톤"]', 10, 15, 0, 5, 25, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('고수(실란트로)', 'herb', '🌿', 3, 2.1, 0.1, 3.7, 93, 2.1, '[]', 386, 27, 0, 0, 246, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["린알롤","아네톨"]', 10, 5, 0, 5, 15, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('파슬리', 'herb', '🌿', 5, 2.7, 0.8, 6.3, 88, 1.3, '[]', 421, 133, 0, 0, 1640, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["플라본","아피올"]', 15, 5, 0, 5, 15, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('생강', 'herb', '🫚', 5, 1.8, 0.8, 18, 79, 2, '[]', 0, 5, 0, 0, 0, 0, 0, 0.16, 0, 0, 0, 0, 415, 0, 0, 0, '["진저롤","쇼가올","진저론"]', 5, 5, 0, 5, 15, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('후추', 'herb', '🌿', 2, 10.4, 3.3, 64, 12, 25, '[]', 0, 21, 0, 0, 163, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["피페린","사비닌"]', 10, 5, 0, 5, 25, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('시나몬', 'herb', '🌿', 2, 3.9, 1.2, 81, 10, 53, '[]', 0, 0, 0, 0, 1113, 0, 0, 0, 0, 0, 0, 0, 0, 1002, 0, 0, '["신나밀알데하이드","쿠마린"]', 5, 60, 0, 0, 20, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('카레가루', 'herb', '🌿', 3, 12, 3.3, 45, 12, 20, '[]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 66, 0, '["쿠르쿠민","강황"]', 20, 10, 0, 5, 15, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('강황', 'herb', '🌿', 3, 9.7, 3.1, 44, 12, 21, '[]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 41, 0, '["쿠르쿠민"]', 10, 5, 0, 5, 15, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('와사비', 'herb', '🌿', 2, 4.8, 0.4, 8.3, 87, 0.8, '[]', 0, 27, 0, 0, 28, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["알릴이소티오시아네이트","글루코시놀레이트"]', 10, 5, 0, 10, 30, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('산초', 'herb', '🌿', 2, 5.4, 8.7, 60, 13, 25, '[]', 0, 0, 0, 0, 1104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, '["히드록시알파산초올"]', 15, 10, 0, 10, 20, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('소금', 'sauce', '🫗', 5, 0, 0, 0, 0, 0, '[]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39146, 0, 0, 0, 0, '["염화나트륨"]', 0, 0, 100, 0, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('식초', 'sauce', '🫗', 15, 0.2, 0, 0.9, 94, 0, '[]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 34, 0, 0, 0, '["아세트산","폴리페놀"]', 0, 0, 0, 95, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('고추장', 'sauce', '🫗', 15, 5, 4.4, 13, 69, 2, '["글루탐산"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1090, 0, 0, 2.2, 0, '["캡사이신","멜라노이딘"]', 35, 20, 70, 20, 10, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('간장', 'sauce', '🫗', 15, 8, 0, 5, 67, 0, '["글루탐산"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5637, 212, 0, 1.9, 0, '["멜라노이딘","글루탐산나트륨","유기산"]', 95, 15, 90, 10, 10, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('설탕', 'sauce', '🍬', 10, 0, 0, 100, 0, 0, '[]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["수크로스","글루코스","프럭토스"]', 0, 100, 0, 0, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('굴소스', 'sauce', '🫗', 15, 5, 0, 7, 87, 0, '["글루탐산"]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1920, 0, 0, 5, 0, '["글루탐산나트륨"]', 80, 20, 80, 5, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('미림', 'sauce', '🫗', 15, 0.4, 0, 40, 54, 0, '[]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 15, 0, 0, 0, '["글루코스","말토스"]', 5, 85, 5, 0, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('물엿', 'sauce', '🫗', 20, 0, 0, 100, 0, 0, '[]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["글루코스","수크로스"]', 0, 95, 0, 0, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('케첩', 'sauce', '🫗', 15, 0.2, 0, 29, 67, 0, '[]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1110, 0, 0, 0, 0, '["리코펜","글루탐산"]', 35, 50, 40, 20, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('마요네즈', 'sauce', '🫗', 15, 0.1, 79, 0.1, 16, 0, '[]', 0, 0, 0, 16.6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["지방","계란 레시틴"]', 5, 5, 30, 15, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('머스타드', 'sauce', '🫗', 10, 3.3, 4.7, 6.4, 80, 3.3, '[]', 0, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 0, 70, 0, 0, '["알릴이소티오시아네이트"]', 10, 10, 30, 30, 20, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('꿀', 'sauce', '🍯', 15, 0.3, 0, 82, 17, 0, '[]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["글루코스","프럭토스"]', 0, 95, 0, 5, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('올리브오일', 'oil', '🫒', 15, 0, 100, 0, 0, 0, '[]', 0, 0, 0, 14.35, 60.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["올레산","폴리페놀","토코페롤"]', 0, 0, 0, 0, 20, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('참기름', 'oil', '🫒', 15, 0, 100, 0, 0, 0, '[]', 0, 0, 0, 1.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["세사몰","세사민"]', 5, 0, 0, 0, 25, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('들기름', 'oil', '🫒', 15, 0, 100, 0, 0, 0, '[]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["알파리놀렌산"]', 5, 0, 0, 0, 20, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('포도씨유', 'oil', '🫒', 15, 0, 100, 0, 0, 0, '[]', 0, 0, 0, 1.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["리놀레산","폴리페놀"]', 0, 0, 0, 0, 10, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('코코넛오일', 'oil', '🫒', 15, 0, 100, 0, 0, 0, '[]', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["라우르산","미리스트산"]', 0, 0, 0, 0, 5, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('카놀라유', 'oil', '🫒', 15, 0, 100, 0, 0, 0, '[]', 0, 0, 0, 15.4, 145, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["올레산","리놀레산"]', 0, 0, 0, 0, 0, 'USDA', true);
INSERT INTO public.ingredients (name, cat, emoji, default_g, protein, fat, carbs, water, fiber, amino_acids, vit_a, vit_c, vit_d, vit_e, vit_k, vit_b1, vit_b2, vit_b6, vit_b12, folate, niacin, sodium, potassium, calcium, iron, zinc, compounds, flavor_umami, flavor_sweet, flavor_salty, flavor_sour, flavor_bitter, source, verified) VALUES ('버터', 'oil', '🧈', 15, 0.9, 81, 0.1, 18, 0, '[]', 684, 0, 0.6, 2.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '["부티르산","디아세틸","카세인","유당"]', 5, 10, 10, 5, 0, 'USDA', true);

-- Migration complete: 136 ingredients inserted

